export enum Images {
  PLACEHOLDER_IMAGE = require('./placeholder.webp'),
  SPLASH_SCREEN = require('./splash_logo.png'),
  ONBOARDING_1 = require('./on_1.png'),
  ONBOARDING_2 = require('./on_2.png'),
  ONBOARDING_3 = require('./ob_3.png'),
  BACK_ICON = require('./app_back.png'),
  PET_OWNER = require('./pet-owner.png'),
  GROOMER = require('./groomer.png'),
  VETE = require('./vete.png'),
  NEXT_ICON = require('./next_icon.png'),
  APP_LOGO = require('./app_logo.png'),
  EMAIL_ICON = require('./email.png'),
  PS_ICON = require('./ps.png'),
  GOOGLE_ICON = require('./google.png'),
  FACEBOOK_ICON = require('./facebook.png'),
  OR_ICON = require('./or.png'),
  CALL_ICON = require('./call.png'),
  PERSON = require('./person.png'),
  ADD_PROFILE = require('./add_profile_pic.png'),
  PROFILE_CHECK = require('./profile_check.png'),
  B_NAME = require('./b_name.png'),
  L_NAME = require('./l_name.png'),
  WORKING = require('./working.png'),
  B_ADDRESS = require('./b_address.png'),
  UPLOAD_PDF = require('./upload_pd.png'),
  DROP_DOWN = require('./dropdown.png'),
  RUPEE = require('./rupee.png'),
  ADD_ANOTHER = require('./add_another_service.png'),
  CAMERA = require('./camera.png'),
  PLUS = require('./plus.png'),
  TIME_ICON = require('./time.png'),
  HOME_ICON = require('./home.png'),
  BOOKING_ICON = require('./bookings.png'),
  ALERT_ICON = require('./alert.png'),
  CLIENT_ICON = require('./client.png'),
  PROFILE_ICON = require('./profile.png'),
  NOTIFICATION_ICON = require('./notification.png'),
  CHAT_ICON = require('./chat.png'),
  DASH_11 = require('./dash_11.png'),
  DASH_12 = require('./dash_12.png'),
  DASH_121 = require('./dash_121.png'),
  DASH_111 = require('./dash_111.png'),
  DASH_21 = require('./dash_21.png'),
  DASH_22 = require('./dash_22.png'),
  DASH_23 = require('./dash_23.png'),
  DASH_24 = require('./dash_24.png'),
  DUMMY1 = require('./dummy1.png'),

  DASH_31 = require('./dash_31.png'),
  DASH_32 = require('./dash_32.png'),
  DASH_33 = require('./dash_33.png'),
  DASH_34 = require('./dash_34.png'),
  CALL2 = require('./call2.png'),
  CHAT2 = require('./chat2.png'),
  PLUS_PURPLE = require('./plus-purple.png'),


  CALENDAR = require('./calender.png'),
  EDIT_PEN = require('./edit-pen.png'),
  LOCK_ICON = require('./lock.png'),
  LOGOUT_ICON = require('./logout.png'),
  QUESTION_ICON = require('./question.png'),
  SERVICE_ICON = require('./service.png'),
  STAR_ICON = require('./star.png'),
  TERMS_CONDITIONS = require('./terms.png'),


  FILTER = require('./filter.png'),
  PLUS_RIGHT = require('./plus-right.png'),
  SEARCH = require('./search.png'),
  CHAT_RED_ICON = require('./chat-redicon.png'),
  ALERT_EMERGENCY = require('./alert-emergency.png'),

  CHECK_SUCCESS = require('./check-success.png'),
  CHAT_PURPLE = require("./chat-purple.png")
}
